// Builds every theme into dist/<name>/ and derives a framework-free
// tokens.css from the same source.
//
//   node scripts/build.mjs          write dist/
//   node scripts/build.mjs --check  fail if committed dist/ is stale
//
// dist/ is committed: consumers install this repo as a git dependency, and
// pnpm does not run build scripts for git dependencies by default.

import {execFileSync} from 'node:child_process';
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';

const root = path.resolve(import.meta.dirname, '..');
const check = process.argv.includes('--check');
const themes = [{name: 'jazz', source: 'themes/jazz/jazzTheme.ts', exportName: 'jazzTheme'}];

let stale = [];

for (const theme of themes) {
  const outDir = path.join('dist', theme.name);
  mkdirSync(path.join(root, outDir), {recursive: true});

  // Astryx compares its own outputs (css, js, d.ts) under --check.
  try {
    execFileSync(
      'pnpm',
      ['exec', 'astryx', 'theme', 'build', theme.source, '--out', `${outDir}/${theme.name}.css`, ...(check ? ['--check'] : [])],
      {cwd: root, stdio: ['ignore', 'ignore', 'inherit']},
    );
  } catch {
    stale.push(`${outDir}/${theme.name}.{css,js,d.ts}`);
  }

  const tokensPath = path.join(root, outDir, 'tokens.css');
  const tokens = await tokensCss(theme);
  if (!check) {
    writeFileSync(tokensPath, tokens);
  } else if (!existsSync(tokensPath) || readFileSync(tokensPath, 'utf8') !== tokens) {
    stale.push(`${outDir}/tokens.css`);
  }
}

if (stale.length) {
  console.error(`Stale build output, run \`pnpm build\` and commit:\n  ${stale.join('\n  ')}`);
  process.exit(1);
}

// Every Astryx token, fully resolved for both modes, on :root. This is the
// contract for code that does not render Astryx components (Vue, Svelte,
// plain CSS): it needs no Astryx runtime and no data-astryx-theme attribute.
async function tokensCss(theme) {
  const {resolveThemeTokens} = await import('@astryxdesign/core/theme');
  const mod = await import(pathToFileURL(path.join(root, theme.source)).href);
  const defined = mod[theme.exportName];
  const light = resolveThemeTokens(defined, {mode: 'light'});
  const dark = resolveThemeTokens(defined, {mode: 'dark'});
  const lines = Object.keys(light)
    .sort()
    .map((name) => {
      const l = light[name];
      const d = dark[name] ?? l;
      return `  ${name}: ${l === d ? l : `light-dark(${l}, ${d})`};`;
    });
  return [
    `/* @generated by scripts/build.mjs from ${theme.source}. Do not edit. */`,
    '',
    ':root {',
    '  color-scheme: light dark;',
    ...lines,
    '}',
    '',
    ':root[data-theme="light"] { color-scheme: light; }',
    ':root[data-theme="dark"] { color-scheme: dark; }',
    '',
  ].join('\n');
}
